export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILURE_LOGIN = 'FAILURE_LOGIN';

export const REQUEST_KEY = 'REQUEST_KEY';
export const SUCCESS_KEY = 'SUCCESS_KEY';
export const FAILURE_KEY = 'FAILURE_KEY';

export const REQUEST_DELKEY = 'REQUEST_DELKEY';
export const SUCCESS_DELKEY = 'SUCCESS_DELKEY';
export const FAILURE_DELKEY = 'FAILURE_DELKEY';

export const REQUEST_ADDKEY = 'REQUEST_ADDKEY';
export const SUCCESS_ADDKEY = 'SUCCESS_ADDKEY';
export const FAILURE_ADDKEY = 'FAILURE_ADDKEY';

export const EXIST_ERROR_MESSAGE = 'EXIST_ERROR_MESSAGE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
